vich_uploader:
    db_driver: orm

    mappings:
        comments:
            uri_prefix: /images/comments
            upload_destination: '%kernel.project_dir%/public/images/comments'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer


